version: '3.6'

services:
  # API
  api:
    container_name: recreo-reglas-api
    restart: always
    build: ./api
    ports:
      - '4002:4002'
    expose:
      - 4002
    volumes:
      - ./api:/usr/src/api

  # SERVER
  server:
    container_name: recreo-reglas-server
    restart: always
    build: ./server
    ports:
      - '4001:4001'
    expose:
      - 4001
    volumes:
      - ./server:/usr/src/server
    depends_on:
      - api

  # CLIENT
  client:
    container_name: recreo-reglas-client
    restart: always
    build: ./client
    ports:
      - '4000:3000'
    expose:
      - 4000
    volumes:
      - ./client:/usr/src/client
    depends_on:
      - server
